config/routes.rb
Rails.application.routes.draw do
  resources :repas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repa.rb
class Repa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/repas_controller.rb
class RepasController < ApplicationController
  before_action :set_repa, only: [:show, :edit, :update, :destroy]

  # GET /repas
  # GET /repas.json
  def index
    @repas = Repa.all
  end

  # GET /repas/1
  # GET /repas/1.json
  def show
  end

  # GET /repas/new
  def new
    @repa = Repa.new
  end

  # GET /repas/1/edit
  def edit
  end

  # POST /repas
  # POST /repas.json
  def create
    @repa = Repa.new(repa_params)

    respond_to do |format|
      if @repa.save
        format.html { redirect_to @repa, notice: 'Repa was successfully created.' }
        format.json { render :show, status: :created, location: @repa }
      else
        format.html { render :new }
        format.json { render json: @repa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repas/1
  # PATCH/PUT /repas/1.json
  def update
    respond_to do |format|
      if @repa.update(repa_params)
        format.html { redirect_to @repa, notice: 'Repa was successfully updated.' }
        format.json { render :show, status: :ok, location: @repa }
      else
        format.html { render :edit }
        format.json { render json: @repa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repas/1
  # DELETE /repas/1.json
  def destroy
    @repa.destroy
    respond_to do |format|
      format.html { redirect_to repas_url, notice: 'Repa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repa
      @repa = Repa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repa_params
      params.require(:repa).permit(:time, :recette, :prix)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repas_helper.rb
module RepasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raph</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repas/_form.html.erb
<%= form_for(repa) do |f| %>
  <% if repa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repa.errors.count, "error") %> prohibited this repa from being saved:</h2>

      <ul>
      <% repa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :time %>
  </div>

  <div class="field">
    <%= f.label :recette %>
    <%= f.text_area :recette %>
  </div>

  <div class="field">
    <%= f.label :prix %>
    <%= f.text_field :prix %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repas/edit.html.erb
<h1>Editing Repa</h1>

<%= render 'form', repa: @repa %>

<%= link_to 'Show', @repa %> |
<%= link_to 'Back', repas_path %>

app/views/repas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repas</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Recette</th>
      <th>Prix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repas.each do |repa| %>
      <tr>
        <td><%= repa.time %></td>
        <td><%= repa.recette %></td>
        <td><%= repa.prix %></td>
        <td><%= link_to 'Show', repa %></td>
        <td><%= link_to 'Edit', edit_repa_path(repa) %></td>
        <td><%= link_to 'Destroy', repa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repa', new_repa_path %>

app/views/repas/new.html.erb
<h1>New Repa</h1>

<%= render 'form', repa: @repa %>

<%= link_to 'Back', repas_path %>

app/views/repas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @repa.time %>
</p>

<p>
  <strong>Recette:</strong>
  <%= @repa.recette %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @repa.prix %>
</p>

<%= link_to 'Edit', edit_repa_path(@repa) %> |
<%= link_to 'Back', repas_path %>